name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Instalar Dependências
      run: pip install -r requirements.txt

    - name: Rodar Testes
      run: pytest

    - name: Construir Imagem Docker
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/pipeline-automatizado:${{ github.sha }} .

    - name: Logar no Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push da Imagem Docker
      run: docker push ${{ secrets.DOCKER_USERNAME }}/pipeline-automatizado:${{ github.sha }}

    - name: Deploy para AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        # Comandos para deploy na AWS usando CLI ou outra ferramenta
        echo "Implementando na AWS..."
